### ISSUE TITLE
Create save_signal function with savesig alias

### ISSUE THREAD

**Issue by billallen256** [dspftw/dspftw#10]

**Comment by willispetersen** [comment]
This function should take an array (complex or real) and save it to a file.  The input parameters should be:

filename
array
data type (same possibilities as loadsig, default = 32f)
real/complex = (default to whether or not the input array is real or complex)
endianness (default = native machine format)

Should return how many elements in the array it saved.

For the real/complex part, we want the ability to save a real file as complex so I need the ability to force that instead of having it check whether or not it's real or complex.

**Comment by billallen256** [comment]
This is done.  If you find an issue, open a new ticket.
