### ISSUE TITLE
Create save_bits function with savebits alias

### ISSUE THREAD

**Issue by billallen256** [dspftw/dspftw#11]

**Comment by willispetersen** [comment]
This function should take a numpy array of bools or 0's and 1's (possibly floats or ints) and pack them into bytes and then save the bytes.  The only input parameters should be:

filename
array

The output should be how many bytes were saved.

We may want a packbit flag so that we can specify leaving the bits as 1 bit per byte in the output (that might be handy) but if we do put that in, the default should be packed bits.

**Comment by billallen256** [comment]
Ok, this appears to be working for both packed and unpacked options.
