### ISSUE TITLE
Create load_signal function with loadsig alias

### ISSUE THREAD

**Issue by billallen256** [dspftw/dspftw#7]

**Comment by willispetersen** [comment]
It should be able to load 8t (signed byte), 16t (signed short), 32t (signed long), 32f (float32) and 64f (float64) each either being big-endian or little-endian and each either being real or complex (20 possible combinations total).

You should also be able to specify how many samples to load as well as a starting sample number.  Defaults should be load all samples and start at sample 0.

This should then return a numpy array containing the data.  For signed int data (8t, 16t, 32t), it should also divide all incoming data by 2**(8-1), 2**(16-1) or 2**(32-1) respectively in order to scale the values that were loaded.

**Comment by gershwinlabs** [comment]
I've started on this, and the underlying data type class.

**Comment by gershwinlabs** [comment]
This should be ready for testing, once we have test data.
