### ISSUE TITLE
Create load_bits function with loadbits alias

### ISSUE THREAD

**Issue by billallen256** [dspftw/dspftw#8]

**Comment by willispetersen** [comment]
This function should load the bits of a file into a dtype=='bool' numpy array.  The input parameters should be:

filename
number of bits to load (default = All)
starting bit (default = 0)

It should probably read the file a byte at a time rather than a short or int at a time so that we don't have to worry about endianness.

**Comment by gershwinlabs** [comment]
This should be ready for testing.
